# Generated by Django 3.1 on 2020-08-15 12:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0003_auto_20200815_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('url', models.URLField(blank=True, verbose_name='url')),
                ('text', models.TextField(verbose_name='context')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created_time')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='article')),
            ],
            options={
                'verbose_name': 'comments',
                'verbose_name_plural': 'comments',
            },
        ),
    ]
